### ISSUE TITLE
Initial thoughts:

### ISSUE THREAD

**Issue by Kuro-dev** [StoneLabs/strains-of-ascension#1]
1. the name is misleading, shouldn't it be "strains of descension" since it gets harder the further you descend?
2. I believe that mining fatigue 3 is a little overkill, that would make it quite impossible to mine anything anymore. Rather use blindness or slowness, possibly add a potion to counter the effects of the mining fatigue instead. Like a "Spelunker potion" that rids of the effects of the depth for a limited time. 
Cheers, let me know if you need help

**Comment by StoneLabs** [comment]
My thoughts:
1. Yes I somewhat agree. However, the name is inspired by the popular anime series "Made in Abyss".
2. I agree. We are currently testing multiple configurations (including the nether). Mining fatigue 3 will most most likely be changed to 1. The effects of blindness are negatable using the night vision effect (only in layers 5-6). I'll add a picture of the current configuration, which is, more or less here to stay.

![image](https://user-images.githubusercontent.com/19885942/109834756-d2211000-7c42-11eb-83f9-023f585ea11d.png)

(0) means negatable using night vision poison (which will run out at 20x speed)
0R means given on a random basis. (Average of once every 2 minutes). Therefore negatable using enough milk.

The version including this will be 2.0.0 which will be released later today.

**Comment by StoneLabs** [comment]
Addressed/Fixed in [Release v2.0.0](https://github.com/StoneLabs/strains-of-ascension/releases/tag/v2.0.0).

Thank you for your great feedback though!
