### ISSUE TITLE
Message submissions

### ISSUE THREAD

**Issue by Kuro-dev** [StoneLabs/strains-of-ascension#2]
[messages.txt](https://github.com/StoneLabs/strains-of-ascension/files/6078622/messages.txt)
I hope this works, but here are a couple of submissions for me in a parsable manner, if you want to make a parser that is, if now i can also offer to make it :D

**Comment by Kuro-dev** [comment]
Could also make it in Json format if that'd be better

**Comment by StoneLabs** [comment]
I've gone ahead and added your messages with 9759d7ef08c69dbbdff25a2e73a2c9150c24d607 (hardcoded for now)


Ideally, we would have some kind of localization file for the server. This is new currently planned though. **Feel free to open another issue with regards to a localization file.** I'll close this one for now.

What I'm not sure how I feel about are the messages you put under `[SLOWNESS]` and `[NAUSEA] `. My idea behind the messages was more of the sort of going crazy. The player having a mental breakdown as one of the strains. I'm not sure if more "meta" so to speak messages would fit that idea.

**Comment by StoneLabs** [comment]
Released with [v2.2.0](https://github.com/StoneLabs/strains-of-ascension/releases/tag/v2.2.0).
